import type {
  AnomalyReport,
  CaseQueue,
  ModelMetrics,
  OperationsOverview,
  SourceMeta,
} from './types';

const demoSource: SourceMeta = {
  sourceKind: 'synthetic_offline_demo',
  snapshotId: 'offline-demo-v1',
  generatedAt: '2026-08-01T09:00:00Z',
  isDemo: true,
  isVerifiedPublicData: false,
  dataMode: 'synthetic_offline_demo',
  persistenceMode: 'browser_local_only',
};

export const demoCases: CaseQueue = {
  source: demoSource,
  total: 6,
  cases: [
    {
      id: 'demo-1001',
      complaintId: 'DEMO-1001',
      dateReceived: '2026-07-31',
      product: 'Credit reporting or other personal consumer reports',
      issue: 'Incorrect information on your report',
      subProduct: 'Credit reporting',
      subIssue: 'Information belongs to someone else',
      company: 'Synthetic Financial Services A',
      state: 'PA',
      narrative:
        '[Synthetic offline demo narrative] The consumer says an account they do not recognize remains on their credit report after two disputes. They say supporting documents were supplied but the item was not removed.',
      companyResponse: 'Closed with explanation',
      timelyResponse: true,
      submissionChannel: 'Web',
      predictedRoute: 'Incorrect information on your report',
      predictedProduct: 'Credit reporting or other personal consumer reports',
      predictedIssue: 'Incorrect information on your report',
      confidence: 0.48,
      abstained: true,
      manualAttention: true,
      attentionReasons: ['Model abstained', 'Identity-related allegation'],
      priority: 'urgent',
      status: 'new',
      ageDays: 1,
      sourceKind: 'synthetic_offline_demo',
    },
    {
      id: 'demo-1002',
      complaintId: 'DEMO-1002',
      dateReceived: '2026-07-30',
      product: 'Debt collection',
      issue: 'Attempts to collect debt not owed',
      subProduct: 'Credit card debt',
      subIssue: 'Debt was already paid',
      company: 'Synthetic Recovery Group',
      state: 'TX',
      narrative:
        '[Synthetic offline demo narrative] The consumer states that a paid balance is still being collected and that they have received repeated calls after sending proof of payment.',
      companyResponse: 'In progress',
      timelyResponse: null,
      submissionChannel: 'Web',
      predictedRoute: 'Communication tactics',
      predictedProduct: 'Debt collection',
      predictedIssue: 'Communication tactics',
      confidence: 0.64,
      abstained: false,
      manualAttention: true,
      attentionReasons: ['Predicted route differs from published issue'],
      priority: 'high',
      status: 'in_review',
      ageDays: 2,
      sourceKind: 'synthetic_offline_demo',
    },
    {
      id: 'demo-1003',
      complaintId: 'DEMO-1003',
      dateReceived: '2026-07-30',
      product: 'Checking or savings account',
      issue: 'Managing an account',
      subProduct: 'Checking account',
      subIssue: 'Deposits and withdrawals',
      company: 'Synthetic Community Bank',
      state: 'OH',
      narrative:
        '[Synthetic offline demo narrative] The consumer reports that a cash deposit was not reflected in the available balance and says branch staff could not provide an expected resolution date.',
      companyResponse: 'Closed with monetary relief',
      timelyResponse: true,
      submissionChannel: 'Phone',
      predictedRoute: 'Managing an account',
      predictedProduct: 'Checking or savings account',
      predictedIssue: 'Managing an account',
      confidence: 0.89,
      abstained: false,
      manualAttention: false,
      attentionReasons: [],
      priority: 'standard',
      status: 'routed',
      ageDays: 2,
      sourceKind: 'synthetic_offline_demo',
    },
    {
      id: 'demo-1004',
      complaintId: 'DEMO-1004',
      dateReceived: '2026-07-29',
      product: 'Mortgage',
      issue: 'Trouble during payment process',
      subProduct: 'Conventional home mortgage',
      subIssue: null,
      company: 'Synthetic Home Lending',
      state: 'FL',
      narrative:
        '[Synthetic offline demo narrative] The consumer says an automatic payment was applied twice and that the duplicate amount has not been returned.',
      companyResponse: 'In progress',
      timelyResponse: null,
      submissionChannel: 'Web',
      predictedRoute: 'Trouble during payment process',
      predictedProduct: 'Mortgage',
      predictedIssue: 'Trouble during payment process',
      confidence: 0.77,
      abstained: false,
      manualAttention: true,
      attentionReasons: ['Open response', 'Potential financial harm'],
      priority: 'high',
      status: 'new',
      ageDays: 3,
      sourceKind: 'synthetic_offline_demo',
    },
    {
      id: 'demo-1005',
      complaintId: 'DEMO-1005',
      dateReceived: '2026-07-28',
      product: 'Credit card',
      issue: 'Problem with a purchase shown on your statement',
      subProduct: 'General-purpose credit card',
      subIssue: 'Card purchase shown multiple times',
      company: 'Synthetic Card Company',
      state: 'CA',
      narrative: null,
      companyResponse: 'Closed with explanation',
      timelyResponse: false,
      submissionChannel: 'Referral',
      predictedRoute: null,
      predictedProduct: null,
      predictedIssue: null,
      confidence: null,
      abstained: true,
      manualAttention: true,
      attentionReasons: ['No published narrative', 'Untimely response'],
      priority: 'high',
      status: 'new',
      ageDays: 4,
      sourceKind: 'synthetic_offline_demo',
    },
    {
      id: 'demo-1006',
      complaintId: 'DEMO-1006',
      dateReceived: '2026-07-27',
      product: 'Money transfer, virtual currency, or money service',
      issue: 'Fraud or scam',
      subProduct: 'Mobile or digital wallet',
      subIssue: null,
      company: 'Synthetic Payments Network',
      state: 'NY',
      narrative:
        '[Synthetic offline demo narrative] The consumer says a transfer was made after an impersonation scam and asks the provider to investigate the recipient account.',
      companyResponse: 'Closed with explanation',
      timelyResponse: true,
      submissionChannel: 'Web',
      predictedRoute: 'Fraud or scam',
      predictedProduct: 'Money transfer, virtual currency, or money service',
      predictedIssue: 'Fraud or scam',
      confidence: 0.93,
      abstained: false,
      manualAttention: true,
      attentionReasons: ['Fraud allegation'],
      priority: 'urgent',
      status: 'in_review',
      ageDays: 5,
      sourceKind: 'synthetic_offline_demo',
    },
  ],
};

export const demoOverview: OperationsOverview = {
  totalComplaints: 6438,
  newComplaints: 418,
  manualAttention: 137,
  timelyRate: 0.941,
  abstentionRate: 0.184,
  medianAgeDays: 2.8,
  volumeChange: 0.087,
  periodLabel: 'Synthetic 30-day demo',
  series: [
    { period: 'W1', count: 1320, timelyRate: 0.936 },
    { period: 'W2', count: 1482, timelyRate: 0.942 },
    { period: 'W3', count: 1661, timelyRate: 0.947 },
    { period: 'W4', count: 1975, timelyRate: 0.941 },
  ],
  products: [
    { label: 'Credit reporting', count: 1984, share: 0.308 },
    { label: 'Debt collection', count: 1247, share: 0.194 },
    { label: 'Credit card', count: 981, share: 0.152 },
    { label: 'Checking or savings', count: 844, share: 0.131 },
    { label: 'Mortgage', count: 653, share: 0.101 },
  ],
  source: demoSource,
};

export const demoAnomalies: AnomalyReport = {
  source: demoSource,
  anomalies: [
    {
      id: 'demo-anomaly-1',
      period: '2026-W31',
      product: 'Credit reporting',
      issue: 'Incorrect information on your report',
      observed: 316,
      expected: 214,
      zScore: 3.4,
      direction: 'up',
      severity: 'high',
      explanation: 'Synthetic count is above its rolling baseline; an operator should inspect narratives before drawing a conclusion.',
    },
    {
      id: 'demo-anomaly-2',
      period: '2026-W31',
      product: 'Debt collection',
      issue: 'Attempts to collect debt not owed',
      observed: 141,
      expected: 108,
      zScore: 2.2,
      direction: 'up',
      severity: 'medium',
      explanation: 'Synthetic increase crossed the monitoring threshold but may reflect normal variation.',
    },
    {
      id: 'demo-anomaly-3',
      period: '2026-W31',
      product: 'Mortgage',
      issue: 'Trouble during payment process',
      observed: 54,
      expected: 71,
      zScore: -1.7,
      direction: 'down',
      severity: 'watch',
      explanation: 'Synthetic volume is below baseline; no operational action is recommended without review.',
    },
  ],
};

export const demoModelMetrics: ModelMetrics = {
  modelName: 'TF-IDF calibrated linear classifier',
  modelVersion: 'offline-demo',
  target: 'Issue label',
  validationWindow: 'Synthetic chronological illustration only',
  macroF1: 0.712,
  accuracy: 0.781,
  expectedCalibrationError: 0.043,
  coverage: 0.816,
  abstentionRate: 0.184,
  abstentionThreshold: 0.62,
  evaluatedRows: 12000,
  falseRoutes: [
    { actual: 'Attempts to collect debt not owed', predicted: 'Communication tactics', count: 84, share: 0.12 },
    { actual: 'Incorrect information on your report', predicted: 'Improper use of your report', count: 63, share: 0.09 },
    { actual: 'Managing an account', predicted: 'Problem with a lender or other company charging your account', count: 42, share: 0.06 },
  ],
  calibration: [
    { lower: 0.5, upper: 0.6, meanConfidence: 0.56, accuracy: 0.53, count: 1110 },
    { lower: 0.6, upper: 0.7, meanConfidence: 0.65, accuracy: 0.63, count: 2430 },
    { lower: 0.7, upper: 0.8, meanConfidence: 0.75, accuracy: 0.73, count: 3180 },
    { lower: 0.8, upper: 0.9, meanConfidence: 0.85, accuracy: 0.84, count: 3370 },
    { lower: 0.9, upper: 1, meanConfidence: 0.94, accuracy: 0.92, count: 1910 },
  ],
  drift: [
    { period: '2026-05', product: 'All products', macroF1: 0.724, abstentionRate: 0.172, driftScore: 0.07, status: 'stable' },
    { period: '2026-06', product: 'All products', macroF1: 0.718, abstentionRate: 0.179, driftScore: 0.11, status: 'watch' },
    { period: '2026-07', product: 'All products', macroF1: 0.712, abstentionRate: 0.184, driftScore: 0.13, status: 'watch' },
  ],
  // No manual review has taken place for the offline fallback. Never invent this metric.
  summaryFactuality: null,
  summaryClaimsSupportedRate: null,
  summaryQuotesExactRate: null,
  summaryReviewedN: 0,
  latencyP50Ms: 284,
  latencyP95Ms: 791,
  meanApiCostUsd: 0.0018,
  systemFailures: 3,
  refusalRate: 0.012,
  source: demoSource,
};
